use serde::{Deserialize, Serialize};
use serde_big_array::BigArray;

use crate::errors::SyntheticError;

/// Represents a TWAMP frame.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum Frame {
  ServerGreeting(ServerGreetingFrame),
  SetUpResponse(SetupResponseFrame),
  ServerStart(ServerStartFrame),
  RequestSession(RequestSessionFrame),
}

impl Frame {
  /// Checks if the provided byte stream and returns the Frame
  pub fn is_valid(&self) -> Result<Self, SyntheticError> {
    todo!();
  }
}

///   The server greeting frame required for connection handshake.
///
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                      Unused (12 octets)                       |
///   |                                                               |
///   |+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                            Modes                              |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                     Challenge (16 octets)                     |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        Salt (16 octets)                       |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                        Count (4 octets)                       |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        MBZ (12 octets)                        |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
/// Challenge is a random sequence of octets generated by the server; it
/// is used subsequently by the client to prove possession of a shared
/// secret in a manner prescribed below.
///
/// Salt and Count are parameters used in deriving a key from a shared
/// secret as described below.
///
/// Salt MUST be generated pseudo-randomly (independently of anything
/// else in this document).
///
/// Count MUST be a power of 2.  Count MUST be at least 1024.  Count
/// SHOULD be increased as more computing power becomes common.
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ServerGreetingFrame {
  pub unused: [u8; 12],
  pub mode: ServerGreetingMode,
  pub challenge: [u8; 16],
  pub salt: [u8; 16],
  pub count: u32,
  pub mbz: [u8; 12],
}

impl ServerGreetingFrame {
  pub fn with_mode(mode: ServerGreetingMode) -> Self {
    Self {
      unused: [0; 12],
      mode,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_unavailable() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Unavailable,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_unauthenticated() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Unauthenticated,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_authenticated() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Authenticated,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_encrypted() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Encrypted,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }
}

/// The client MUST respond with the following Set-Up-Response message:
///
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                             Mode                              |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   .                                                               .
///   .                       KeyID (80 octets)                       .
///   .                                                               .
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   .                                                               .
///   .                       Token (64 octets)                       .
///   .                                                               .
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   .                                                               .
///   .                     Client-IV (16 octets)                     .
///   .                                                               .
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
///
/// Here Mode is the mode that the client chooses to use during this
/// TWAMP-Control session.  It will also be used for all TWAMP-Test
/// sessions started under control of this OWAMP-Control session.  In
/// Mode, one or zero bits MUST be set within last three bits.  If it is
/// one bit that is set within the last three bits, this bit MUST
/// indicate a mode that the server agreed to use (i.e., the same bit
/// MUST have been set by the server in the server greeting).  The first
/// 29 bits of Mode MUST be zero.  A server MUST ignore the values of the
/// first 29 bits.  If zero Mode bits are set by the client, the client
/// indicates that it will not continue with the session; in this case,
/// the client and the server SHOULD close the TCP connection associated
/// with the OWAMP-Control session.
///
/// In unauthenticated mode, KeyID, Token, and Client-IV are unused.
/// Otherwise, KeyID is a UTF-8 string, up to 80 octets in length (if the
/// string is shorter, it is padded with zero octets), that tells the
/// server which shared secret the client wishes to use to authenticate
/// or encrypt, while Token is the concatenation of a 16-octet challenge,
/// a 16-octet AES Session-key used for encryption, and a 32-octet HMAC-
/// SHA1 Session-key used for authentication.  The token itself is
/// encrypted using the AES (Advanced Encryption Standard) in
/// Cipher Block Chaining (CBC). Encryption MUST be performed using an
/// Initialization Vector (IV) of zero and a key derived from the shared
/// secret associated with KeyID.  (Both the server and the client use
/// the same mappings from KeyIDs to shared secrets.  The server, being
/// prepared to conduct sessions with more than one client, uses KeyIDs
/// to choose the appropriate secret key; a client would typically have
/// different secret keys for different servers.  The situation is
/// analogous to that with passwords.)
///
/// The shared secret is a passphrase; it MUST not contain newlines.  The
/// secret key is derived from the passphrase using a password-based key
/// derivation function PBKDF2 (PKCS #5) RFC2898.  The PBKDF2 function
/// requires several parameters: the PRF is HMAC-SHA1 RFC2104; the salt
/// and count are as transmitted by the server.
///
/// AES Session-key, HMAC Session-key and Client-IV are generated
/// randomly by the client.  AES Session-key and HMAC Session-key MUST be
/// generated with sufficient entropy not to reduce the security of the
/// underlying cipher RFC4086.  Client-IV merely needs to be unique
/// (i.e., it MUST never be repeated for different sessions using the
/// same secret key; a simple way to achieve that without the use of
/// cumbersome state is to generate the Client-IV values using a
/// cryptographically secure pseudo-random number source:  if this is
/// done, the first repetition is unlikely to occur before 2^64 sessions
/// with the same secret key are conducted).
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct SetupResponseFrame {
  pub mode: ServerGreetingMode,
  #[serde(with = "BigArray")]
  pub key_id: [u8; 80],
  #[serde(with = "BigArray")]
  pub token: [u8; 64],
  pub client_iv: [u8; 16],
}

impl SetupResponseFrame {
  pub fn with_mode(mode: ServerGreetingMode) -> Self {
    match mode {
      ServerGreetingMode::Authenticated => todo!(),
      ServerGreetingMode::Unauthenticated => Self {
        mode,
        key_id: [0; 80],
        token: [0; 64],
        client_iv: [0; 16],
      },
      ServerGreetingMode::Unavailable => todo!(),
      ServerGreetingMode::Encrypted => todo!(),
    }
  }
}

/// Meaningful Server Greeting Mode Values
///
/// - 0: The server is not willing to accept any more sessions.
/// - 1: for unauthenticated
/// - 2: for authenticated
/// - 4 for encrypted.
///
/// The value of the Modes field sent by the server is the bit-wise OR of the
/// mode values that it is willing to support during this session. Thus, the
/// last three bits of the Modes 32-bit value are used.  The first
/// 29 bits MUST be zero.  A client MUST ignore the values in the first 29 bits
/// of the Modes value.  
///
/// > This way, the bits are available for future protocol extensions.
/// > This is the only intended extension mechanism.)
///
/// If the Modes value is zero, the server does not wish to communicate
/// with the client and MAY close the connection immediately.  The client
/// SHOULD close the connection if it receives a greeting with Modes
/// equal to zero.  The client MAY close the connection if the client's
/// desired mode is unavailable.
#[repr(u32)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum ServerGreetingMode {
  Unavailable = 0,
  Unauthenticated = 1,
  Authenticated = 2,
  Encrypted = 4,
}

/// The server MUST respond with the following Server-Start message:
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |                         MBZ (15 octets)                       |
///    |                                                               |
///    |                                               +-+-+-+-+-+-+-+-+
///    |                                               |   Accept      |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |                     Server-IV (16 octets)                     |
///    |                                                               |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                     Start-Time (Timestamp)                    |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                         MBZ (8 octets)                        |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
/// The MBZ parts MUST be zero.  The client MUST ignore their value.  MBZ
/// (MUST be zero) fields here and after have the same semantics: the
/// party that sends the message MUST set the field so that all bits are
/// equal to zero; the party that interprets the message MUST ignore the
/// value.  (This way, the field could be used for future extensions.)
/// Server-IV is generated randomly by the server.  In unauthenticated
/// mode, Server-IV is unused.
/// The Accept field indicates the server's willingness to continue
/// communication.  A zero value in the Accept field means that the
/// server accepts the authentication and is willing to conduct further
/// transactions.  Non-zero values indicate that the server does not
/// accept the authentication or, for some other reason, is not willing
/// to conduct further transactions in this OWAMP-Control session.  The
/// full list of available Accept values is described in Section 3.3,
/// "Values of the Accept Field".
/// If a negative (non-zero) response is sent, the server MAY (and the
/// client SHOULD) close the connection after this message.
/// Start-Time is a timestamp representing the time when the current
/// instantiation of the server started operating.  (For example, in a
/// multi-user general purpose operating system, it could be the time
/// when the server process was started.)  If Accept is non-zero, Start-
///  Time SHOULD be set so that all of its bits are zeros.  In
///  authenticated and encrypted modes, Start-Time is encrypted as
///  described in Section 3.4, "OWAMP-Control Commands", unless Accept is
///  non-zero.  (Authenticated and encrypted mode cannot be entered unless
///  the control connection can be initialized.)
///  Timestamp format is described in Section 4.1.2.  The same
///  instantiation of the server SHOULD report the same exact Start-Time
///  value to each client in each session.
///  The previous transactions constitute connection setup.
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ServerStartFrame {
  pub mbz1: [u8; 15],
  pub accept: ServerStartAccept,
  pub server_iv: [u8; 16],
  pub mbz2: [u8; 8],
}

/// The full set of valid Server-Start accept value as described in RFC.   
///
/// Accept values are used throughout the TWAMP-Control protocol to
/// communicate the server response to client requests.  The full set of
/// valid Accept field values are as follows:
///
///    - 0    OK.
///    - 1    Failure, reason unspecified (catch-all).
///    - 2    Internal error.
///    - 3    Some aspect of request is not supported.
///    - 4    Cannot perform request due to permanent resource limitations.
///    - 5    Cannot perform request due to temporary resource limitations.
///
///   All other values are reserved.  The sender of the message MAY use the
///  value of 1 for all non-zero Accept values.  A message sender SHOULD
///  use the correct Accept value if it is going to use other values.  The
///  message receiver MUST interpret all values of Accept other than these
///  reserved values as 1.  This way, other values are available for
///  future extensions.
#[repr(u8)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum ServerStartAccept {
  Ok = 0,
  Failure = 1,
  InternalError = 2,
  RequestNotSupported = 3,
  PermanentResourceLimitation = 4,
  TemporaryResourceLimitation = 5,
}

/// Test session creation follows the same procedure as defined in
/// Section 3.5 of OWAMP [RFC4656].  The Request-TW-Session command is
/// based on the OWAMP Request-Session command, and uses the message
/// format as described in Section 3.5 of OWAMP, but without the Schedule
/// Slot Descriptions field(s) and uses only one HMAC.  The description
/// of the Request-TW-Session format follows.
/// 
/// If a TWAMP Server receives an unexpected Command Number, it MUST
/// respond with the Accept field set to 3 (meaning "Some aspect of
/// request is not supported") in the Accept-Session message.  Command
/// Numbers that are Forbidden (and possibly numbers that are Reserved)
/// are unexpected.
/// 
/// In OWAMP, the Conf-Sender field is set to 1 when the Request-Session
/// message describes a task where the Server will configure a one-way
/// test packet sender.  Likewise, the Conf-Receiver field is set to 1
/// when the message describes the configuration for a Session-Receiver.
/// In TWAMP, both endpoints send and receive test packets, with the
/// Session-Sender first sending and then receiving test packets,
/// complimented by the Session-Reflector first receiving and then
/// sending.
/// 
/// Both the Conf-Sender field and Conf-Receiver field MUST be set to 0
/// since the Session-Reflector will both receive and send packets, and
/// the roles are established according to which host initiates the TCP
/// connection for control.  The Server MUST interpret any non-zero value
/// as an improperly formatted command, and MUST respond with the Accept
/// field set to 3 (meaning "Some aspect of request is not supported") in
/// the Accept-Session message.
/// 
/// The Session-Reflector in TWAMP does not process incoming test packets
/// for performance metrics and consequently does not need to know the
/// number of incoming packets and their timing schedule.  Consequently
/// the Number of Scheduled Slots and Number of Packets MUST be set to 0.
/// The Sender Port is the UDP port from which TWAMP-Test packets will be
/// sent and the port to which TWAMP-Test packets will be sent by the
/// Session-Reflector (the Session-Sender will use the same UDP port to
/// send and receive packets).  The Receiver Port is the desired UDP port
/// to which TWAMP-Test packets will be sent by the Session-Sender (the
/// port where the Session-Reflector is asked to receive test packets).
/// The Receiver Port is also the UDP port from which TWAMP-Test packets
/// will be sent by the Session-Reflector (the Session-Reflector will use
/// the same UDP port to send and receive packets).
/// 
/// The Sender Address and Receiver Address fields contain, respectively,
/// the sender and receiver addresses of the endpoints of the Internet
/// path over which a TWAMP-Test session is requested.  They MAY be set
/// to 0, in which case the IP addresses used for the Control-Client to
/// Server TWAMP-Control message exchange MUST be used in the test
/// packets.
/// 
/// The Session Identifier (SID) is as defined in OWAMP [RFC4656].  Since
/// the SID is always generated by the receiving side, the Server
/// determines the SID, and the SID in the Request-TW-Session message
/// MUST be set to 0.
/// 
/// The Start Time is as defined in OWAMP [RFC4656].
/// 
/// The Timeout is interpreted differently from the definition in OWAMP
/// [RFC4656].  In TWAMP, Timeout is the interval that the Session-
/// Reflector MUST wait after receiving a Stop-Sessions message.  In case
/// there are test packets still in transit, the Session-Reflector MUST
/// reflect them if they arrive within the Timeout interval following the
/// reception of the Stop-Sessions message.  The Session-Reflector MUST
/// NOT reflect packets that are received beyond the timeout.
/// Type-P descriptor is as defined in OWAMP [RFC4656].  The only
/// capability of this field is to set the Differentiated Services Code
/// Point (DSCP) as defined in [RFC2474].  The same value of DSCP MUST be
/// used in test packets reflected by the Session-Reflector.
/// Since there are no Schedule Slot Descriptions, the Request-TW-Session
/// message is completed by MBZ (Must Be Zero) and HMAC fields.  This
/// completes one logical message, referred to as the Request-TW-Session
/// command.
/// 
/// The Session-Reflector MUST respond to each Request-TW-Session command
/// with an Accept-Session message as defined in OWAMP [RFC4656].  When
/// the Accept field = 0, the Port field confirms (repeats) the port to
/// which TWAMP-Test packets are sent by the Session-Sender toward the
/// Session-Reflector.  In other words, the Port field indicates the port
/// number where the Session-Reflector expects to receive packets from
/// the Session-Sender.
/// 
/// When the requested Receiver Port is not available (e.g., port in
/// use), the Server at the Session-Reflector MAY suggest an alternate
/// and available port for this session in the Port field.  The Session-
/// Sender either accepts the alternate port, or composes a new Session-
/// Request message with suitable parameters.  Otherwise, the Server at
/// the Control-Client uses the Accept field to convey other forms of
/// session rejection or failure and MUST NOT suggest an alternate port;
/// in this case, the Port field MUST be set to zero.
/// 
/// ## The format of Request-Session message is as follows:
/// ```text
///     0                   1                   2                   3
///     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |      1        |  MBZ  | IPVN  |  Conf-Sender  | Conf-Receiver |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                  Number of Schedule Slots                     |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                      Number of Packets                        |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |          Sender Port          |         Receiver Port         |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                        Sender Address                         |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |           Sender Address (cont.) or MBZ (12 octets)           |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                        Receiver Address                       |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |           Receiver Address (cont.) or MBZ (12 octets)         |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |                        SID (16 octets)                        |
///    |                                                               |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                         Padding Length                        |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                           Start Time                          |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                       Timeout, (8 octets)                     |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                       Type-P Descriptor                       |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                         MBZ (8 octets)                        |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |                       HMAC (16 octets)                        |
///    |                                                               |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
///  Above, the first octet (1) indicates that this is the Request-Session
///  command.
/// 
///  IPVN is the IP version numbers for Sender and Receiver.  When the IP
///  version number is 4, 12 octets follow the 4-octet IPv4 address stored
///  in Sender Address and Receiver Address.  These octets MUST be set to
///  zero by the client and MUST be ignored by the server.  Currently
///  meaningful IPVN values are 4 and 6.
/// 
///  Conf-Sender and Conf-Receiver MUST be set to 0 or 1 by the client.
///  The server MUST interpret any non-zero value as 1.  If the value is
///  1, the server is being asked to configure the corresponding agent
///  (sender or receiver).  In this case, the corresponding Port value
///  SHOULD be disregarded by the server.  At least one of Conf-Sender and
///  Conf-Receiver MUST be 1.  (Both can be set, in which case the server
///  is being asked to perform a session between two hosts it can
///  configure.)
/// 
///  Number of Packets is the number of active measurement packets to be
///  sent during this OWAMP-Test session (note that either the server or
///  the client can abort the session early).
/// 
///  If Conf-Sender is not set, Sender Port is the UDP port from which
///  OWAMP-Test packets will be sent.  If Conf-Receiver is not set,
///  Receiver Port is the UDP port OWAMP-Test to which packets are
///  requested to be sent.
/// 
///  The Sender Address and Receiver Address fields contain, respectively,
///  the sender and receiver addresses of the end points of the Internet
///  path over which an OWAMP test session is requested.
/// 
///  SID is the session identifier.  It can be used in later sessions as
///  an argument for the Fetch-Session command.  It is meaningful only if
///  Conf-Receiver is 0.  This way, the SID is always generated by the
///  receiving side.  See the end of the section for information on how
///  the SID is generated.
/// 
///  Padding length is the number of octets to be appended to the normal
///  OWAMP-Test packet (see more on padding in discussion of OWAMP-Test).
///  Start Time is the time when the session is to be started (but not
///  before Start-Sessions command is issued).  This timestamp is in the
///  same format as OWAMP-Test timestamps.
/// 
///  Timeout (or a loss threshold) is an interval of time (expressed as a
///  timestamp).  A packet belonging to the test session that is being set
///  up by the current Request-Session command will be considered lost if
///  it is not received during Timeout seconds after it is sent.
///  Type-P Descriptor covers only a subset of (very large) Type-P space.
///  If the first two bits of the Type-P Descriptor are 00, then the
///  subsequent six bits specify the requested Differentiated Services
///  Codepoint (DSCP) value of sent OWAMP-Test packets, as defined in
///  [RFC2474].  If the first two bits of Type-P descriptor are 01, then
///  the subsequent 16 bits specify the requested PHB Identification Code
///  (PHB ID), as defined in [RFC2836].
/// 
///  Therefore, the value of all zeros specifies the default best-effort
///  service.
/// 
///  If Conf-Sender is set, the Type-P Descriptor is to be used to
///  configure the sender to send packets according to its value.  If
///  Conf-Sender is not set, the Type-P Descriptor is a declaration of how
///  the sender will be configured.
/// 
///  If Conf-Sender is set and the server does not recognize the Type-P
///  Descriptor, or it cannot or does not wish to set the corresponding
///  attributes on OWAMP-Test packets, it SHOULD reject the session
///  request.  If Conf-Sender is not set, the server SHOULD accept or
///  reject the session, paying no attention to the value of the Type-P
///  Descriptor.
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct RequestSessionFrame {
  pub command_number: u8,
  pub mbz_1: u8,
  pub ipvn: IpVersion,
  pub conf_sender: u8,
  pub conf_receiver: u8,
  pub number_of_scheduled_slots: u32,
  pub number_of_packets: u32,
  pub sender_port: u16,
  pub receiver_port: u16,
  pub sender_address: u32,
  pub sender_mbz: [u8; 12],
  pub receiver_address: u32,
  pub receiver_mbz: [u8; 12],
  pub sid: [u8; 16],
  pub padding_length: u32,
  pub start_time: u32,
  pub time_out: u32,
  pub type_p_descriptor: u32,
  pub mbz: u16,
  pub hmac: [u8; 16],
}

#[repr(u8)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum IpVersion {
  V4 = 4,
  V6 = 6,
}
