//! # Library to measure synthetic traffic. Based on RFC 5357.
//!
//! The library is an implementation of RFC 5357, Two way active measurement
//! protocol. The code organization is based on the RFC's logical model.
//!
//! ## Relationship of Test and Control Protocols
//!
//! OWAMP actually consists of two inter-related protocols: OWAMP-Control
//! and OWAMP-Test.  OWAMP-Control is used to initiate, start, and stop
//! test sessions and to fetch their results, whereas OWAMP-Test is used
//! to exchange test packets between two measurement nodes.
//! Although OWAMP-Test may be used in conjunction with a control
//! protocol other than OWAMP-Control, the authors have deliberately
//! chosen to include both protocols in the same RFC to encourage the
//! implementation and deployment of OWAMP-Control as a common
//! denominator control protocol for one-way active measurements.  Having
//! a complete and open one-way active measurement solution that is
//! simple to implement and deploy is crucial to ensuring a future in
//! which inter-domain one-way active measurement could become as
//! commonplace as ping.  We neither anticipate nor recommend that
//! OWAMP-Control form the foundation of a general-purpose extensible
//! measurement and monitoring control protocol.
//! OWAMP-Control is designed to support the negotiation of one-way
//! active measurement sessions and results retrieval in a
//! straightforward manner.  At session initiation, there is a
//! negotiation of sender and receiver addresses and port numbers,
//! session start time, session length, test packet size, the mean
//! Poisson sampling interval for the test stream, and some attributes of
//! the very general [RFC 2330](https://datatracker.ietf.org/doc/html/rfc2330)
//! notion of packet type, including packet size and per-hop behavior (PHB)
//! [RFC2474](https://datatracker.ietf.org/doc/html/rfc2474), which could be used to
//! support the measurement of one-way network characteristics across
//! differentiated services networks.  Additionally, OWAMP-Control
//! supports per-session encryption and authentication for both test and
//! control traffic, measurement servers that can act as proxies for test
//! stream endpoints, and the exchange of a seed value for the pseudo-
//! random Poisson process that describes the test stream generated by
//! the sender.
//! We believe that OWAMP-Control can effectively support one-way active
//! measurement in a variety of environments, from publicly accessible
//! measurement beacons running on arbitrary hosts to network monitoring
//! deployments within private corporate networks.  If integration with
//! Simple Network Management Protocol (SNMP) or proprietary network
//! management protocols is required, gateways may be created.
//!
//! ## Logical Model
//!
//! Several roles are logically separated to allow for broad flexibility
//! in use.  Specifically, we define the following:
//!
//! ### Session-Sender
//! The sending endpoint of an OWAMP-Test session;
//!
//! ###Session-Receiver
//! The receiving endpoint of an OWAMP-Test session;
//!
//! ### Server
//! An end system that manages one or more OWAMP-Test
//! sessions, is capable of configuring per-session
//! state in session endpoints, and is capable of
//! returning the results of a test session;
//!
//! ### Control-Client   
//! An end system that initiates requests for
//! OWAMP-Test sessions, triggers the start of a set
//! of sessions, and may trigger their termination;
//!
//! ### Fetch-Client
//! An end system that initiates requests to fetch the results of
//! completed OWAMP-Test sessions.
//!
//! ## Flow Diagram
//!
//! ```text
//!        +----------------+               +------------------+
//!        | Session-Sender |--OWAMP-Test-->| Session-Receiver |
//!        +----------------+               +------------------+
//!          ^                                     ^
//!          |                                     |
//!          |                                     |
//!          |                                     |
//!          |  +----------------+<----------------+
//!          |  |     Server     |<-------+
//!          |  +----------------+        |
//!          |    ^                       |
//!          |    |                       |
//!          | OWAMP-Control         OWAMP-Control
//!          |    |                       |
//!          v    v                       v
//!        +----------------+     +-----------------+
//!        | Control-Client |     |   Fetch-Client  |
//!        +----------------+     +-----------------+
//! ```
//!
//! (Unlabeled links in the figure are unspecified by this document and
//! may be proprietary protocols.)
//! Different logical roles can be played by the same host.  For example,
//! in the figure above, there could actually be only two hosts: one
//! playing the roles of Control-Client, Fetch-Client, and Session-
//! Sender, and the other playing the roles of Server and Session-
//! Receiver.  This is shown below.
//!
//! ```text
//!        +-----------------+                   +------------------+
//!        | Control-Client  |<--OWAMP-Control-->| Server           |
//!        | Fetch-Client    |                   |                  |
//!        | Session-Sender  |---OWAMP-Test----->| Session-Receiver |
//!        +-----------------+                   +------------------+
//! ```
//!
//! Finally, because many Internet paths include segments that transport
//! IP over ATM, delay and loss measurements can include the effects of
//! ATM segmentation and reassembly (SAR).  Consequently, OWAMP has been
//! designed to allow for small test packets that would fit inside the
//! payload of a single ATM cell (this is only achieved in unauthenticated mode).

#[warn(missing_debug_implementations, missing_docs)]
pub mod errors;
#[warn(missing_debug_implementations, missing_docs)]
pub mod frames;

#[warn(missing_debug_implementations, missing_docs)]
pub mod io;
