use serde::{Deserialize, Serialize};
use serde_big_array::BigArray;

/// Represents a TWAMP frame.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum Frame {
  ServerGreeting(ServerGreetingFrame),
  SetUpResponse(SetUpResponseFrame),
  ServerStart(ServerStartFrame),
}

impl Frame {
  /// Checks if the provided byte stream is a valid TWAMP frame.
  pub fn is_valid(&self) -> Result<Self, std::io::Error> {
    todo!();
  }
}

///   The server greeting frame required for connection handshake.
///
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                      Unused (12 octets)                       |
///   |                                                               |
///   |+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                            Modes                              |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                     Challenge (16 octets)                     |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        Salt (16 octets)                       |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                        Count (4 octets)                       |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        MBZ (12 octets)                        |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
/// Challenge is a random sequence of octets generated by the server; it
/// is used subsequently by the client to prove possession of a shared
/// secret in a manner prescribed below.
///
/// Salt and Count are parameters used in deriving a key from a shared
/// secret as described below.
///
/// Salt MUST be generated pseudo-randomly (independently of anything
/// else in this document).
///
/// Count MUST be a power of 2.  Count MUST be at least 1024.  Count
/// SHOULD be increased as more computing power becomes common.
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ServerGreetingFrame {
  pub unused: [u8; 12],
  pub mode: ServerGreetingMode,
  pub challenge: [u8; 16],
  pub salt: [u8; 16],
  pub count: u32,
  pub mbz: [u8; 12],
}

impl ServerGreetingFrame {
  pub fn with_mode(mode: ServerGreetingMode) -> Self {
    Self {
      unused: [0; 12],
      mode,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_unavailable() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Unavailable,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_unauthenticated() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Unauthenticated,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_authenticated() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Authenticated,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }

  pub fn mode_encrypted() -> Self {
    Self {
      unused: [0; 12],
      mode: ServerGreetingMode::Encrypted,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }
}

/// The server MUST respond with the following Set-Up-Response message:
///
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                             Mode                              |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   .                                                               .
///   .                       KeyID (80 octets)                       .
///   .                                                               .
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   .                                                               .
///   .                       Token (64 octets)                       .
///   .                                                               .
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   .                                                               .
///   .                     Client-IV (16 octets)                     .
///   .                                                               .
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
///
/// Here Mode is the mode that the client chooses to use during this
/// TWAMP-Control session.  It will also be used for all TWAMP-Test
/// sessions started under control of this OWAMP-Control session.  In
/// Mode, one or zero bits MUST be set within last three bits.  If it is
/// one bit that is set within the last three bits, this bit MUST
/// indicate a mode that the server agreed to use (i.e., the same bit
/// MUST have been set by the server in the server greeting).  The first
/// 29 bits of Mode MUST be zero.  A server MUST ignore the values of the
/// first 29 bits.  If zero Mode bits are set by the client, the client
/// indicates that it will not continue with the session; in this case,
/// the client and the server SHOULD close the TCP connection associated
/// with the OWAMP-Control session.
///
/// In unauthenticated mode, KeyID, Token, and Client-IV are unused.
/// Otherwise, KeyID is a UTF-8 string, up to 80 octets in length (if the
/// string is shorter, it is padded with zero octets), that tells the
/// server which shared secret the client wishes to use to authenticate
/// or encrypt, while Token is the concatenation of a 16-octet challenge,
/// a 16-octet AES Session-key used for encryption, and a 32-octet HMAC-
/// SHA1 Session-key used for authentication.  The token itself is
/// encrypted using the AES (Advanced Encryption Standard) in
/// Cipher Block Chaining (CBC). Encryption MUST be performed using an
/// Initialization Vector (IV) of zero and a key derived from the shared
/// secret associated with KeyID.  (Both the server and the client use
/// the same mappings from KeyIDs to shared secrets.  The server, being
/// prepared to conduct sessions with more than one client, uses KeyIDs
/// to choose the appropriate secret key; a client would typically have
/// different secret keys for different servers.  The situation is
/// analogous to that with passwords.)
///
/// The shared secret is a passphrase; it MUST not contain newlines.  The
/// secret key is derived from the passphrase using a password-based key
/// derivation function PBKDF2 (PKCS #5) RFC2898.  The PBKDF2 function
/// requires several parameters: the PRF is HMAC-SHA1 RFC2104; the salt
/// and count are as transmitted by the server.
///
/// AES Session-key, HMAC Session-key and Client-IV are generated
/// randomly by the client.  AES Session-key and HMAC Session-key MUST be
/// generated with sufficient entropy not to reduce the security of the
/// underlying cipher RFC4086.  Client-IV merely needs to be unique
/// (i.e., it MUST never be repeated for different sessions using the
/// same secret key; a simple way to achieve that without the use of
/// cumbersome state is to generate the Client-IV values using a
/// cryptographically secure pseudo-random number source:  if this is
/// done, the first repetition is unlikely to occur before 2^64 sessions
/// with the same secret key are conducted).
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct SetUpResponseFrame {
  pub mode: ServerGreetingMode,
  #[serde(with = "BigArray")]
  pub key_id: [u8; 80],
  #[serde(with = "BigArray")]
  pub token: [u8; 64],
  pub client_iv: [u8; 16],
}

impl SetUpResponseFrame {
  pub fn mode_unauthenticated() -> Self {
    Self {
      mode: ServerGreetingMode::Unauthenticated,
      key_id: [0; 80],
      token: [0; 64],
      client_iv: [0; 16],
    }
  }
}

/// Meaningful Server Greeting Mode Values
///
/// - 0: The server is not willing to accept any more sessions.
/// - 1: for unauthenticated
/// - 2: for authenticated
/// - 4 for encrypted.
///
/// The value of the Modes field sent by the server is the bit-wise OR of the
/// mode values that it is willing to support during this session. Thus, the
/// last three bits of the Modes 32-bit value are used.  The first
/// 29 bits MUST be zero.  A client MUST ignore the values in the first 29 bits
/// of the Modes value.  
///
/// > This way, the bits are available for future protocol extensions.
/// > This is the only intended extension mechanism.)
///
/// If the Modes value is zero, the server does not wish to communicate
/// with the client and MAY close the connection immediately.  The client
/// SHOULD close the connection if it receives a greeting with Modes
/// equal to zero.  The client MAY close the connection if the client's
/// desired mode is unavailable.
#[repr(u32)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum ServerGreetingMode {
  Unavailable = 0,
  Unauthenticated = 1,
  Authenticated = 2,
  Encrypted = 4,
}

/// The server MUST respond with the following Server-Start message:
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |                         MBZ (15 octets)                       |
///    |                                                               |
///    |                                               +-+-+-+-+-+-+-+-+
///    |                                               |   Accept      |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                                                               |
///    |                     Server-IV (16 octets)                     |
///    |                                                               |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                     Start-Time (Timestamp)                    |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///    |                         MBZ (8 octets)                        |
///    |                                                               |
///    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
/// The MBZ parts MUST be zero.  The client MUST ignore their value.  MBZ
/// (MUST be zero) fields here and after have the same semantics: the
/// party that sends the message MUST set the field so that all bits are
/// equal to zero; the party that interprets the message MUST ignore the
/// value.  (This way, the field could be used for future extensions.)
/// Server-IV is generated randomly by the server.  In unauthenticated
/// mode, Server-IV is unused.
/// The Accept field indicates the server's willingness to continue
/// communication.  A zero value in the Accept field means that the
/// server accepts the authentication and is willing to conduct further
/// transactions.  Non-zero values indicate that the server does not
/// accept the authentication or, for some other reason, is not willing
/// to conduct further transactions in this OWAMP-Control session.  The
/// full list of available Accept values is described in Section 3.3,
/// "Values of the Accept Field".
/// If a negative (non-zero) response is sent, the server MAY (and the
/// client SHOULD) close the connection after this message.
/// Start-Time is a timestamp representing the time when the current
/// instantiation of the server started operating.  (For example, in a
/// multi-user general purpose operating system, it could be the time
/// when the server process was started.)  If Accept is non-zero, Start-
///  Time SHOULD be set so that all of its bits are zeros.  In
///  authenticated and encrypted modes, Start-Time is encrypted as
///  described in Section 3.4, "OWAMP-Control Commands", unless Accept is
///  non-zero.  (Authenticated and encrypted mode cannot be entered unless
///  the control connection can be initialized.)
///  Timestamp format is described in Section 4.1.2.  The same
///  instantiation of the server SHOULD report the same exact Start-Time
///  value to each client in each session.
///  The previous transactions constitute connection setup.
#[repr(packed)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ServerStartFrame {
  pub mbz1: [u8; 15],
  pub accept: ServerStartAccept,
  pub server_iv: [u8; 16],
  pub mbz2: [u8; 8],
}

/// The full set of valid Server-Start accept value as described in RFC.   
///
/// Accept values are used throughout the TWAMP-Control protocol to
/// communicate the server response to client requests.  The full set of
/// valid Accept field values are as follows:
///
///    - 0    OK.
///    - 1    Failure, reason unspecified (catch-all).
///    - 2    Internal error.
///    - 3    Some aspect of request is not supported.
///    - 4    Cannot perform request due to permanent resource limitations.
///    - 5    Cannot perform request due to temporary resource limitations.
///
///   All other values are reserved.  The sender of the message MAY use the
///  value of 1 for all non-zero Accept values.  A message sender SHOULD
///  use the correct Accept value if it is going to use other values.  The
///  message receiver MUST interpret all values of Accept other than these
///  reserved values as 1.  This way, other values are available for
///  future extensions.
#[repr(u8)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum ServerStartAccept {
  Ok = 0,
  Failure = 1,
  InternalError = 2,
  RequestNotSupported = 3,
  PermanentResourceLimitation = 4,
  TemporaryResourceLimitation = 5,
}
