use super::Mode;
use byteme::ByteMe;
use num_traits::FromPrimitive;
///   The server greeting frame required for connection handshake.
///
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                      Unused (12 octets)                       |
///   |                                                               |
///   |+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                            Modes                              |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                     Challenge (16 octets)                     |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        Salt (16 octets)                       |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                        Count (4 octets)                       |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        MBZ (12 octets)                        |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
///
/// Salt and Count are parameters used in deriving a key from a shared
/// secret as described below.
///
/// Salt MUST be generated pseudo-randomly (independently of anything
/// else in this document).
///
/// Count MUST be a power of 2.  Count MUST be at least 1024.  Count
/// SHOULD be increased as more computing power becomes common.
#[repr(packed)]
#[derive(Debug, Clone, Copy, ByteMe)]
pub struct ServerGreetingFrame {
  /// Unused, for future enhancement
  pub unused: [u8; 12],
  /// The mode in which the server is wiling to accept connections
  #[byte_me(u32)]
  pub mode: Mode,
  /// Challenge is a random sequence of octets generated by the server; it
  /// is used subsequently by the client to prove possession of a shared
  /// secret in a manner prescribed below.
  pub challenge: [u8; 16],
  /// Salt MUST be generated pseudo-randomly (independently of anything
  /// else in this document).
  pub salt: [u8; 16],
  /// Count MUST be a power of 2.  Count MUST be at least 1024.  Count
  /// SHOULD be increased as more computing power becomes common.
  pub count: u32,
  /// normally zero.
  pub mbz: [u8; 12],
}

impl ServerGreetingFrame {
  /// give a mode, generates a server greeting frame
  pub fn with_mode(mode: Mode) -> Self {
    Self {
      unused: [0; 12],
      mode,
      challenge: [0; 16],
      salt: [0; 16],
      count: 1024,
      mbz: [0; 12],
    }
  }
}
