use crate::common::{generate_random_sequence, IsValid, Reply};

use super::{Mode, SetupResponseFrame};
use byteme::ByteMe;
use tracing::debug;

///   The server greeting frame required for connection handshake.
///
/// ```text
///    0                   1                   2                   3
///    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                      Unused (12 octets)                       |
///   |                                                               |
///   |+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                            Modes                              |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                     Challenge (16 octets)                     |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        Salt (16 octets)                       |
///   |                                                               |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                        Count (4 octets)                       |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
///   |                                                               |
///   |                        MBZ (12 octets)                        |
///   |                                                               |
///   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
/// ```
///
/// Salt and Count are parameters used in deriving a key from a shared
/// secret as described below.
///
/// Salt MUST be generated pseudo-randomly (independently of anything
/// else in this document).
///
/// Count MUST be a power of 2.  Count MUST be at least 1024.  Count
/// SHOULD be increased as more computing power becomes common.
#[repr(packed)]
#[derive(Debug, Clone, Copy, ByteMe)]
pub struct ServerGreetingFrame {
  /// Unused, for future enhancement
  pub unused: [u8; 12],
  /// The mode in which the server is wiling to accept connections
  #[byte_me(u32)]
  pub mode: Mode,
  /// Challenge is a random sequence of octets generated by the server; it
  /// is used subsequently by the client to prove possession of a shared
  /// secret in a manner prescribed below.
  pub challenge: [u8; 16],
  /// Salt MUST be generated pseudo-randomly (independently of anything
  /// else in this document).
  pub salt: [u8; 16],
  /// Count MUST be a power of 2.  Count MUST be at least 1024.  Count
  /// SHOULD be increased as more computing power becomes common.
  pub count: u32,
  /// normally zero.
  pub mbz: [u8; 12],
}

impl ServerGreetingFrame {
  /// give a mode, generates a server greeting frame
  pub fn new(mode: Mode) -> Self {
    match mode {
      Mode::Authenticated | Mode::Encrypted => Self {
        unused: [0; 12],
        mode,
        challenge: Self::generate_challenge(),
        salt: Self::generate_salt(),
        count: 1024,
        mbz: [0; 12],
      },
      Mode::Unauthenticated | Mode::Unavailable => Self {
        unused: [0; 12],
        mode,
        challenge: [0; 16],
        salt: [0; 16],
        count: 1024,
        mbz: [0; 12],
      },
    }
  }

  /// generates the challenge
  pub fn generate_challenge() -> [u8; 16] {
    let challenge: [u8; 16] = generate_random_sequence(16).as_bytes().try_into().unwrap();
    challenge
  }

  /// generates the salt
  pub fn generate_salt() -> [u8; 16] {
    let salt: [u8; 16] = generate_random_sequence(16).as_bytes().try_into().unwrap();
    salt
  }
}

impl Reply for ServerGreetingFrame {
  type Response = SetupResponseFrame;

  fn reply(&self) -> Self::Response {
    debug!("Composing Reply for: {:?}", self);
    match self.mode {
      Mode::Unauthenticated | Mode::Unavailable => SetupResponseFrame::new(self.mode),
      Mode::Authenticated => todo!(),
      Mode::Encrypted => todo!(),
    }
  }
}

impl IsValid for ServerGreetingFrame {
  fn is_valid(&self) -> bool {
    match self.mode {
      Mode::Unavailable | Mode::Unauthenticated => {
        self.unused == [0; 12]
          && self.challenge == [0; 16]
          && self.salt == [0; 16]
          && self.count == 1024
          && self.mbz == [0; 12]
      }
      Mode::Authenticated | Mode::Encrypted => {
        self.unused == [0; 12]
          && self.challenge != [0; 16]
          && self.salt != [0; 16]
          && self.count == 1024
          && self.mbz == [0; 12]
      }
    }
  }
}

#[cfg(test)]
mod tests {
  use super::{Mode, ServerGreetingFrame, SetupResponseFrame};
  use crate::common::{IsValid, Reply};

  #[test]
  fn create_with_mode_unauthetnicated() {
    let mode = Mode::Unauthenticated;
    let frame: Vec<u8> = ServerGreetingFrame::new(mode).into();
    let frame: ServerGreetingFrame = frame.into();
    let is_valid = frame.is_valid();
    assert!(is_valid);
  }

  #[test]
  fn reply_with_mode_unauthenticated() {
    let mode = Mode::Unauthenticated;
    let response = SetupResponseFrame::new(mode);
    let frame = ServerGreetingFrame::new(mode);
    let reply = frame.reply();
    assert_eq!(response, reply);
  }

  #[test]
  fn create_with_mode_unavailable() {
    let mode = Mode::Unavailable;
    let frame: Vec<u8> = ServerGreetingFrame::new(mode).into();
    let frame: ServerGreetingFrame = frame.into();
    let is_valid = frame.is_valid();
    assert!(is_valid);
  }

  #[test]
  fn reply_with_mode_unavailable() {
    let mode = Mode::Unavailable;
    let response = SetupResponseFrame::new(mode);
    let frame = ServerGreetingFrame::new(mode);
    let reply = frame.reply();
    assert_eq!(response, reply);
  }
}
